demo_dbt_kh:
  outputs:
    dev:
      dataset: us_east_region_aws_useast1_uat_monolith
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /Users/kristyhan/Documents/Scripts/Creds/eds/uat_creds.json
      location: US
      method: service-account
      priority: interactive
      project: fivetran-fountain-warehouse
      threads: 1
      type: bigquery
  target: dev
jaffle_shop:
  outputs:
    dev:
      dataset: us_east_region_aws_useast1_uat_monolith
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /Users/kristyhan/Documents/Scripts/Creds/uat_creds.json
      location: US
      method: service-account
      priority: interactive
      project: fivetran-fountain-warehouse
      threads: 1
      type: bigquery
  target: dev
my-profile:
  outputs:
    dev:
      dataset: us_east_region_aws_useast1_uat_monolith
      method: oauth
      project: fivetran-fountain-warehouse
      type: bigquery
  target: dev
